### ISSUE TITLE
Merging the JOSM-Scripts to the Mapathoner plugin

### ISSUE THREAD

**Issue by ghost** [MikeTho16/JOSM-Scripts#1]
Hi @MikeTho16.  This is more *asking-you-for-a-favor* issue.

The `JOSM-Scripts` are being used (not only) for the humanitarian mapping. However, necessity of the [JOSM Scripting Plugin](https://gubaer.github.io/josm-scripting-plugin/) to run scripts limits the possible audience. Personally, I had the same problem when I was creating some of my first scripts. I solved that with the [Mapathoner plugin](https://qeef.gitlab.io/mapathoner/).

Now the favor I am asking you for. I would like to *merge JOSM-Scripts into the Mapathoner plugin*. The changes are here:

https://gitlab.com/qeef/mapathoner/-/merge_requests/3

It would be awesome if you, as the original author, can review the changes.

Thanks,
jiri

**Comment by MikeTho16** [comment]
Hi Jiri,

Are you asking for my permission? You of course don't really need it, but
you have it.  It is an honor that my scripts are being used and have been
chosen to be included.

Are you asking me to review the code?  I just looked at it briefly, and the
one thing that jumped out is that in the duplicate building part you are
not making a spatial index of the buildings first that I noticed.  You have
a nested for loop, which is O(n^2) I think, and will run very slowly if
there are a lot of buildings. When I first created this script I did it
without the index, and someone almost immediately complained.  A spatial
index makes it more like O(n log n)... much better.   I can look at it
further if you like.

Mike

**Comment by ghost** [comment]
Hi Mike,

thanks for the prompt reply!

> Are you asking for my permission?

I am really happy you agree.

> Are you asking me to review the code?

Thanks for the review! I just updated the code adding the quad buckets:

https://gitlab.com/qeef/mapathoner/-/commit/d187ca131985cfccfd5c5690259df64f0e2fb7b4

That was exactly I was asking for,
jiri

**Comment by MikeTho16** [comment]
Here is another comment:

I don't think this:
Geometry.polygonIntersection(Geometry.getArea(w.getNodes()),
Geometry.getArea(w2.getNodes()), 0.5)
is going to work in the way you intend (although I might be wrong).  My
understanding is that the eps, in this case 0.5, is in the same units as
the areas, which in this case is lat/lon (almost nonsensical way to measure
"area", but given that we are checking for overlap and the areas are small,
it works). The original intent in the script was that the 0.5 represented a
percentage (50%) of overlap below which a building would not be selected.

Mike

**Comment by ghost** [comment]
> I don't think this:
Geometry.polygonIntersection(Geometry.getArea(w.getNodes()),
Geometry.getArea(w2.getNodes()), 0.5)
is going to work in the way you intend

You are right. I tried to dig a bit deeper and found https://josm.openstreetmap.de/browser/josm/trunk/src/org/openstreetmap/josm/tools/Geometry.java#L668

If I understand it correctly, areas intersect if some segment of the intersection is greater than `eps`. I think that I fixed it here:

https://gitlab.com/qeef/mapathoner/-/commit/e0472d7929b432615449a24d5bcab8059a6e2f31

Again, with a help of your scripts!

Thank you very much for your feedback, I do appreticiate it a lot!
jiri

**Comment by MikeTho16** [comment]
[SelectDuplicateBuildingsAction.java.zip](https://github.com/MikeTho16/JOSM-Scripts/files/5467740/SelectDuplicateBuildingsAction.java.zip)

Jiri,

I wrote and tested my version of SelectDuplicateBuildingsAction.java  , it should be attached.  I included tons of comments so you could know the reasons I choose to do it a certain way.  

Mike

**Comment by ghost** [comment]
Grateful thanks, Mike!

I merged your implementation:

https://gitlab.com/qeef/mapathoner/-/commit/b235d44b21b4cf59d984d7485367b2abe8ff533c

I did only changed some cosmetics issues as indentation or wrapping to keep in line with the rest of the files.

Many thanks,
jiri

**Comment by MikeTho16** [comment]
Jiri,

You are welcome!

I understand about the style, everyone has their own style.  I think it is
a debate as old as programming itself.  I don't think that Java has a style
guide like Python ( PEP 8). I try to follow the standard of the core JOSM
code, except I am currently indenting 2 rather than 4 spaces... but I
probably should change that.

Regarding SelectNonOrthogonalBuildingAction.java.  I think it has some of
the same issues as in SelectDuplicateBuildingAction.java, such as you are
only operating on the current view,vs all of the data in a layer, and you
are toggling the selection, rather than setting it.


*Mike*

**Comment by ghost** [comment]
Hi Mike,

I realized it when you sent your code of `SelectDuplicateBuildingsAction`, so I changed it, too

https://gitlab.com/qeef/mapathoner/-/merge_requests/3/diffs?commit_id=870ece3b58710f21933b96c2fbb531f794d83493

I am really very thankful for your feedback.

I am going to merge these changes to the `master` branch, wait a while because of the translations, and release new version as soon as the new JOSM tested is out (in the matter of days it should be.) I will close this issue when this happens, if it's OK. If anything comes to your mind, I will be always happy to listen :)

Thanks again!
jiri

**Comment by ghost** [comment]
It took ages, but it's finally [released](https://gitlab.com/qeef/mapathoner/-/tags/v1.1.0) and [announced](https://lists.openstreetmap.org/pipermail/hot/2020-November/015392.html).

I am closing this issue now.

Thanks!

**Comment by MikeTho16** [comment]
Fantastic!
